API_VERSION = '2.0'
JSON_ENDPOINT = 'https://api.datamarket.azure.com/Bing/Search/v1/Composite'
MAX_PAGE_SIZE = 50
MAX_RESULTS = 1000

WEB_SOURCE_TYPE = 'Web'
IMAGE_SOURCE_TYPE = 'Image'
NEWS_SOURCE_TYPE = 'News'
SPELL_SOURCE_TYPE = 'Spell'
RELATED_SOURCE_TYPE = 'RelatedSearch'
PHONEBOOK_SOURCE_TYPE = 'Phonebook'
ANSWERS_SOURCE_TYPE = 'InstanceAnswer'

SOURCE_TYPES = (
    WEB_SOURCE_TYPE,
    IMAGE_SOURCE_TYPE,
    NEWS_SOURCE_TYPE,
    SPELL_SOURCE_TYPE,
    RELATED_SOURCE_TYPE,
    PHONEBOOK_SOURCE_TYPE,
    ANSWERS_SOURCE_TYPE,
)

DEFAULT_SOURCE_TYPE = WEB_SOURCE_TYPE